title: Tacit Dynamics
description: Developer of FolderSync for Android
theme: jekyll-theme-architect

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins:
  - jekyll-seo-tag

include:
  - .well-known 